In [1]:
import psycopg2 as pg
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
connection = pg.connect("host=localhost dbname=autos_db user=postgres")

In [11]:
title = "Toyota Corolla 2017"
subtitle = "1.3 GLI Super ECT"
df = pd.read_sql(f"SELECT CONCAT(title, ' ', subtitle) AS vehicle_name, highest_bid FROM carfirst_auction WHERE highest_bid > 0 AND updated_at > '2022-03-25' ORDER BY vehicle_name", con=connection)

In [12]:
print(f"Total records: {len(df)}")

Total records: 43

In [13]:
df["highest_bid"] = df["highest_bid"]/100000
df

                                         vehicle_name  highest_bid
0                 Changan Alsvin 2021 1.5 DTC Lumiere     27.14000
1                    Daihatsu Cuore 2007 850cc CX Eco      4.64000
2                          Daihatsu Mira 2014 660cc L     15.04000
3                           Honda City 2000 1.3 EXI S      4.14000
4                          Honda City 2015 1.3 i-VTEC     18.00005
5                          Honda City 2017 1.3 i-VTEC     20.35000
6                          Honda Civic 1994 1.5 EX-EG      4.46000
7                Honda Civic 2004 1.5 EXi - New Shape      8.14000
8                   Honda Civic 2016 1.5 i-VTEC Turbo     32.30000
9                              Honda N 2014 660cc WGN     13.62000
10                Honda N 2014 660cc WGN Custom Turbo     15.74000
11                      Honda N 2016 660cc WGN Custom     17.61000
12                       Mitsubishi Mirage 2014 1.0 M     16.50000
13                             Nissan Dayz 2015 660cc     14.31000
14                           Suzuki Alto 2004 1.0 VXR      2.91000
15                           Suzuki Alto 2004 1.0 VXR      4.83000
16                           Suzuki Alto 2007 1.0 VXR      5.60000
17                 Suzuki Cultus 2014 1.0 VXR Euro II      9.62000
18                         Suzuki Cultus 2020 1.0 VXL     19.14000
19                        Suzuki Mehran 2007 800cc VX      4.52000
20                Suzuki Mehran 2015 800cc VX Euro II      7.00000
21                Suzuki Mehran 2016 800cc VX Euro II      5.50000
22                Suzuki Mehran 2016 800cc VX Euro II      6.52000
23          Suzuki Swift 2017 1.3 DLX with Navigation     17.36000
24                       Suzuki Wagon R 2015 660cc FX     11.47000
25                        Suzuki Wagon R 2021 1.0 VXL     20.24000
26                  Toyota Aqua 2013 1.5 S Push Start     22.72000
27                Toyota Aqua 2015 1.5 G Soft Leather     28.60000
28                             Toyota Axio 2007 1.5 G     20.95000
29             Toyota Corolla 2008 1.3 XLI- Old Shape      8.99000
30                        Toyota Corolla 2012 1.3 GLI     16.38000
31              Toyota Corolla 2012 1.6 GLI Super ECT     18.78000
32                        Toyota Corolla 2013 1.3 GLI     14.40000
33  Toyota Corolla 2014 1.3 GLI - Limited Edition ...     20.11000
34            Toyota Corolla 2014 1.3 XLI - New Shape     19.33000
35            Toyota Corolla 2014 1.3 XLI - Old Shape     15.02000
36              Toyota Corolla 2017 1.3 GLI Super ECT     25.07000
37   Toyota Corolla 2017 1.6 Altis Facelift Super ECT     29.73000
38   Toyota Corolla 2017 1.6 Altis Facelift Super ECT     32.84000
39  Toyota Corolla 2017 1.8 Altis Grande CVT-i - F...     31.25000
40            Toyota Corolla 2018 1.6 Altis Super ECT     34.12000
41  Toyota Corolla 2018 1.8 Grande CVT-i Cruisetronic     32.21000
42              Toyota Land Cruiser 2006 4.0 Prado TZ     65.36000